#!/usr/bin/env bash

# MIT License
#
# Copyright © 2020 Darren Mo.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

SCRIPT_NAME="$(basename "$BASH_SOURCE")"
SCRIPT_DIR="$(dirname "$BASH_SOURCE")"
cd "$SCRIPT_DIR"

OUTPUT_DIR="$(pwd)/Sources/Cuchardet"

cd uchardet/src || exit $?

rm -rf "$OUTPUT_DIR"

mkdir -p "$OUTPUT_DIR"
cp -R *.h *.cpp *.tab LangModels "$OUTPUT_DIR/" || exit $?

mkdir -p "$OUTPUT_DIR/include"
mv "$OUTPUT_DIR/uchardet.h" "$OUTPUT_DIR/include/" || exit $?

GIT_COMMIT_HASH="$(git rev-parse HEAD)"
echo "Source code files copied by \`$SCRIPT_NAME\` from the \`uchardet\` Git repository at commit \`$GIT_COMMIT_HASH\`." \
   >> "$OUTPUT_DIR/VERSION.md"
